// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: structs.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// structs.PromptPart
type PromptPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptPart) Reset() {
	*x = PromptPart{}
	mi := &file_structs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptPart) ProtoMessage() {}

func (x *PromptPart) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptPart.ProtoReflect.Descriptor instead.
func (*PromptPart) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{0}
}

func (x *PromptPart) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PromptPart) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PromptPart) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// structs.PromptMessage
type PromptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*PromptPart          `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptMessage) Reset() {
	*x = PromptMessage{}
	mi := &file_structs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptMessage) ProtoMessage() {}

func (x *PromptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptMessage.ProtoReflect.Descriptor instead.
func (*PromptMessage) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{1}
}

func (x *PromptMessage) GetParts() []*PromptPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// grpcserver.Request
type Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Language        string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	CurrentMessage  *PromptMessage         `protobuf:"bytes,2,opt,name=current_message,json=currentMessage,proto3" json:"current_message,omitempty"`
	HistoryMessages []*PromptMessage       `protobuf:"bytes,3,rep,name=history_messages,json=historyMessages,proto3" json:"history_messages,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_structs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Request) GetCurrentMessage() *PromptMessage {
	if x != nil {
		return x.CurrentMessage
	}
	return nil
}

func (x *Request) GetHistoryMessages() []*PromptMessage {
	if x != nil {
		return x.HistoryMessages
	}
	return nil
}

// grpcserver.Response
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_structs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_structs_proto protoreflect.FileDescriptor

const file_structs_proto_rawDesc = "" +
	"\n" +
	"\rstructs.proto\x12\x14magic_conch_shell.v1\"W\n" +
	"\n" +
	"PromptPart\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"G\n" +
	"\rPromptMessage\x126\n" +
	"\x05parts\x18\x01 \x03(\v2 .magic_conch_shell.v1.PromptPartR\x05parts\"\xc3\x01\n" +
	"\aRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12L\n" +
	"\x0fcurrent_message\x18\x02 \x01(\v2#.magic_conch_shell.v1.PromptMessageR\x0ecurrentMessage\x12N\n" +
	"\x10history_messages\x18\x03 \x03(\v2#.magic_conch_shell.v1.PromptMessageR\x0fhistoryMessages\" \n" +
	"\bResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2Y\n" +
	"\x10AssistantService\x12E\n" +
	"\x04Chat\x12\x1d.magic_conch_shell.v1.Request\x1a\x1e.magic_conch_shell.v1.ResponseB\fZ\n" +
	"../structsb\x06proto3"

var (
	file_structs_proto_rawDescOnce sync.Once
	file_structs_proto_rawDescData []byte
)

func file_structs_proto_rawDescGZIP() []byte {
	file_structs_proto_rawDescOnce.Do(func() {
		file_structs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_structs_proto_rawDesc), len(file_structs_proto_rawDesc)))
	})
	return file_structs_proto_rawDescData
}

var file_structs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_structs_proto_goTypes = []any{
	(*PromptPart)(nil),    // 0: magic_conch_shell.v1.PromptPart
	(*PromptMessage)(nil), // 1: magic_conch_shell.v1.PromptMessage
	(*Request)(nil),       // 2: magic_conch_shell.v1.Request
	(*Response)(nil),      // 3: magic_conch_shell.v1.Response
}
var file_structs_proto_depIdxs = []int32{
	0, // 0: magic_conch_shell.v1.PromptMessage.parts:type_name -> magic_conch_shell.v1.PromptPart
	1, // 1: magic_conch_shell.v1.Request.current_message:type_name -> magic_conch_shell.v1.PromptMessage
	1, // 2: magic_conch_shell.v1.Request.history_messages:type_name -> magic_conch_shell.v1.PromptMessage
	2, // 3: magic_conch_shell.v1.AssistantService.Chat:input_type -> magic_conch_shell.v1.Request
	3, // 4: magic_conch_shell.v1.AssistantService.Chat:output_type -> magic_conch_shell.v1.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_structs_proto_init() }
func file_structs_proto_init() {
	if File_structs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_structs_proto_rawDesc), len(file_structs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_structs_proto_goTypes,
		DependencyIndexes: file_structs_proto_depIdxs,
		MessageInfos:      file_structs_proto_msgTypes,
	}.Build()
	File_structs_proto = out.File
	file_structs_proto_goTypes = nil
	file_structs_proto_depIdxs = nil
}
