// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: structs.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// structs.PromptPart
type PromptPart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *PromptPart) Reset() {
	*x = PromptPart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_structs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromptPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptPart) ProtoMessage() {}

func (x *PromptPart) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptPart.ProtoReflect.Descriptor instead.
func (*PromptPart) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{0}
}

func (x *PromptPart) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PromptPart) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PromptPart) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// structs.PromptMessage
type PromptMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parts []*PromptPart `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
}

func (x *PromptMessage) Reset() {
	*x = PromptMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_structs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptMessage) ProtoMessage() {}

func (x *PromptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptMessage.ProtoReflect.Descriptor instead.
func (*PromptMessage) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{1}
}

func (x *PromptMessage) GetParts() []*PromptPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// grpcserver.Request
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentMessage  *PromptMessage   `protobuf:"bytes,1,opt,name=current_message,json=currentMessage,proto3" json:"current_message,omitempty"`
	HistoryMessages []*PromptMessage `protobuf:"bytes,2,rep,name=history_messages,json=historyMessages,proto3" json:"history_messages,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_structs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetCurrentMessage() *PromptMessage {
	if x != nil {
		return x.CurrentMessage
	}
	return nil
}

func (x *Request) GetHistoryMessages() []*PromptMessage {
	if x != nil {
		return x.HistoryMessages
	}
	return nil
}

// grpcserver.Response
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_structs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_structs_proto protoreflect.FileDescriptor

var file_structs_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x68, 0x65,
	0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x57, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x50,
	0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x47,
	0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x36, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x68, 0x65,
	0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x50, 0x61, 0x72, 0x74,
	0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x22, 0xa7, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d,
	0x61, 0x67, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x4e, 0x0a, 0x10, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x61,
	0x67, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x0f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x22, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x32, 0x59, 0x0a, 0x10, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x1d, 0x2e, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x68,
	0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x68, 0x65,
	0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2e, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_structs_proto_rawDescOnce sync.Once
	file_structs_proto_rawDescData = file_structs_proto_rawDesc
)

func file_structs_proto_rawDescGZIP() []byte {
	file_structs_proto_rawDescOnce.Do(func() {
		file_structs_proto_rawDescData = protoimpl.X.CompressGZIP(file_structs_proto_rawDescData)
	})
	return file_structs_proto_rawDescData
}

var file_structs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_structs_proto_goTypes = []any{
	(*PromptPart)(nil),    // 0: magic_conch_shell.v1.PromptPart
	(*PromptMessage)(nil), // 1: magic_conch_shell.v1.PromptMessage
	(*Request)(nil),       // 2: magic_conch_shell.v1.Request
	(*Response)(nil),      // 3: magic_conch_shell.v1.Response
}
var file_structs_proto_depIdxs = []int32{
	0, // 0: magic_conch_shell.v1.PromptMessage.parts:type_name -> magic_conch_shell.v1.PromptPart
	1, // 1: magic_conch_shell.v1.Request.current_message:type_name -> magic_conch_shell.v1.PromptMessage
	1, // 2: magic_conch_shell.v1.Request.history_messages:type_name -> magic_conch_shell.v1.PromptMessage
	2, // 3: magic_conch_shell.v1.AssistantService.Chat:input_type -> magic_conch_shell.v1.Request
	3, // 4: magic_conch_shell.v1.AssistantService.Chat:output_type -> magic_conch_shell.v1.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_structs_proto_init() }
func file_structs_proto_init() {
	if File_structs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_structs_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PromptPart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_structs_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PromptMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_structs_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_structs_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_structs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_structs_proto_goTypes,
		DependencyIndexes: file_structs_proto_depIdxs,
		MessageInfos:      file_structs_proto_msgTypes,
	}.Build()
	File_structs_proto = out.File
	file_structs_proto_rawDesc = nil
	file_structs_proto_goTypes = nil
	file_structs_proto_depIdxs = nil
}
