name: Publish Discord

on:
  push:
    tags:
      - 'discord/v*.*.*'

jobs:
  publish:
    name: Build & Publish Discord Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Metadata (Discord)
        id: meta-discord
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/magic-conch-shell-discord
          tags: |
            type=match,pattern=discord/v(.*),group=1
            type=raw,value=latest

      - name: Build and Push Discord
        uses: docker/build-push-action@v5
        with:
          context: ./discord
          file: ./discord/docker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-discord.outputs.tags }}
          labels: ${{ steps.meta-discord.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
